ch1/homepage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.home, name="home"),
    url(r'^subject/$', views.subject, name="subject"),
    url(r'^entrance/$', views.entrance, name="entrance"),
    url(r'^news/$', views.news, name="news"),
    url(r'^introduction/$', views.introduction, name="introduction"),
]

ch1/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.shortcuts import render
from django.shortcuts import redirect
from . import views





urlpatterns = [
    url('admin/', admin.site.urls),

    # 리다이렉션
    url(r'^$', views.home),
    url(r'^', include('homepage.urls', namespace='homepage')),
]

ch1/homepage/models.py
from django.db import models

# Create your models here.

ch1/homepage/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def introduction(request):
    return render(request, 'homepage/introduction.html')


def subject(request):
    return render(request, 'homepage/subject.html')


def news(request):
    return render(request, 'homepage/news.html')


def entrance(request):
    return render(request, 'homepage/entrance.html')

ch1/mysite/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

ch1/homepage/templates/homepage/base.html
<!DOCTYPE html>
<html>
    <head>
    {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
    </head>
    <body>
        <header>
            <div id="hdiv">
                <a href="{% url 'homepage:home' %}"><img src="{% static 'img/logo.png' %}" width="190px" height="30px"></a>
                <ul>
                    <li><a href="{% url 'homepage:introduction' %}">학교안내</a></li>
                    <li><a href="{% url 'homepage:subject' %}">교과안내</a></li>
                    <li><a href="{% url 'homepage:news' %}">학교소식</a></li>
                    <li><a href="{% url 'homepage:entrance' %}">입학안내</a></li>
                </ul>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <footer>
            <div id="fdiv">
                <div id="wrap">
                    <div class="fdiv">
                        <ul>
                            <li>학교안내</li>
                            <hr>
                            <li>학교목표</li>
                            <li>교육과정</li>
                            <li>선생님 소개</li>
                            <li>오시는 길</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li>교과안내</li>
                            <hr>
                            <li>공통과목</li>
                            <li>전공과목</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li>학교소식</li>
                            <hr>
                            <li>코딩캠프</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li>입학안내</li>
                            <hr>
                            <li>문의하기</li>
                            <li>전화</li>
                            <li>이메일</li>
                        </ul>
                    </div>
                </div>
                <div id="ffdiv">
                    <p>Copyright ⓒ Seoul Music High School All Rights Reserved.</p>
                    <hr>
                    <p style="color: white;">비즈쿨 대안학교<br>
                        경기도 오산시 고현동 남부대로 429 대표전화 : 031-668-3399 문의: 010-9089-3399</p>
                    <hr>
                </div>    
            </div>
            
        </footer>
    </body>
</html>

ch1/homepage/templates/homepage/entrance.html
{% extends "realbase.html" %}

{% block content %}

<!DOCTYPE hthml>
<html>
    <head>
        <style>
            article #adiv #wrap1{
                width:68%;
                margin: 0 auto;
            }
            article #adiv #adiv1{
                display: inline-block;
                padding: 15px 0;
            }
            article #adiv #adiv2 {
                float: right;
                padding: 15px 0;
            }
            article #adiv #adiv2 ul{
                display: flex;
                list-style: none;
                padding-top:5px;
            }
            article #adiv #adiv2 ul li{
                margin-left: 20px;
            }
            article #adiv #문의{
                padding: 60px 0;
            }
            article #adiv #문의 #연락처{
                display: flex;
                margin: 0 auto;
                width:20%;
            }
            article #adiv #문의 #연락처 div{
                border: 1px solid gray;
                width:600px;
                margin: 30px;
                line-height: 100px;
                text-align:center;
            }
            .contact span{
                display: inline-block;
                margin-bottom:20px;
                font-size: 2.2rem;
                width: 2em;
                line-height: 2em;
                border-radius: 50%;
                text-align: center;
                background-color: #5D9AB2;
                color: #fff;
            }
            contact h2 {
                margin-top: 0;
                font-size: 1.2rem;
            }
            contact a{
                font-size: 1.4rem;
                color: inherit;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <article>
            <div id="adiv">
                <div id="wrap1">
                    <div id="adiv1">
                        <h1>문의하기</h1>
                    </div>
                    <div id="adiv2">  
                        <ul>
                            <li></li>
                            <li></li>
                        </ul>
                    </div>
                    <hr>
                </div>
                <div id="문의">
                    <h1 style="text-align: center;padding-bottom: 30px;font-size: 34px;">문의하기</h1>
                    <div class="contact-wrap">
                        <div class="contact">
                            <span class="fa fa-phone"></span>
                            <h2>전화</h2>
                            <a href="tel:01090893399">010-9089-3399</a>
                        </div>
                            
                        <div class="contact">
                            <span class="fa fa-envelope"></span>
                            <h2>이메일</h2>
                            <a href="mailto:jyh8016@hanmail.net">jyh8016@hanmil.net</a>
                        </div>
                    </div>
                </div>
        </article>
    </body>
</html>


{% endblock %}

ch1/homepage/templates/homepage/home.html
{% extends "homepage/base.html" %}

{% block content %}
<h1>1111</h1>
{% endblock %}

ch1/homepage/templates/homepage/introduction.html
{% extends "realbase.html" %}

{% block content %}
<body>
    <div class="jumbotron">
        <h2 class="text-center">학교소개</h2>
    </div>
    <div class="container">
        <div class="jumbotron">
        </div>
            <h2></h2>
        
    </div>
</body>
{% endblock %}

ch1/homepage/templates/homepage/news.html
{% extends "realbase.html" %}

{% block content %}
<head>
    <style>
        @media (min-width: 768px){
        .wrap {
            padding: 0 20%;
        }
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>학교 소식</h2>
        <div></div>
    </div>
    <div class="jumbotron jumbotron-fluid">
        <div 
    </div>
</body>
{% endblock %}

ch1/homepage/templates/homepage/subject.html
{% extends "realbase.html" %}

{% block content %}
<!DOCTYPE html>
<html>
    <body>
        <div class="container">
            <h2>교과안내</h2>
        </div>
        <div class="jumbotron">
            <div class="container">
                <h2 class="text-center"><strong>협력 업체와 제휴 협약</strong></h2>
            </div>
        </div>    
        <div class="container">
            
        </div>
        <div class="jumbotron">

        </div>
    </body>
</html>
{% endblock %}

ch1/mysite/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
        <!-- bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">

        <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- bootstrap -->
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <header>
            <div id="hdiv">
                <a href="{% url 'homepage:home' %}"><img src="{% static 'img/logo.png' %}" width="190px" height="30px"></a>
                <ul>
                    <li><a href="{% url 'homepage:introduction' %}">학교안내</a></li>
                    <li><a href="{% url 'homepage:subject' %}">교과안내</a></li>
                    <li><a href="{% url 'homepage:news' %}">학교소식</a></li>
                    <li><a href="{% url 'homepage:entrance' %}">입학안내</a></li>
                </ul>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <footer>
            <div id="fdiv">
                <div id="wrap">
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:introduction' %}">학교안내</a></li>
                            <hr>
                            <li>학교목표</li>
                            <li>교육과정</li>
                            <li>선생님 소개</li>
                            <li>오시는 길</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:subject' %}">교과안내</a></li>
                            <hr>
                            <li>공통과목</li>
                            <li>전공과목</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:news' %}">학교소식</a></li>
                            <hr>
                            <li>코딩캠프</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:entrance' %}">입학안내</a></li>
                            <hr>
                            <li>문의하기</li>
                            <li>전화</li>
                            <li>이메일</li>
                        </ul>
                    </div>
                </div>
                <div id="ffdiv">
                    <p>Copyright ⓒ Seoul Music High School All Rights Reserved.</p>
                    <hr>
                    <p style="color: white;">비즈쿨 대안학교<br>
                        경기도 오산시 고현동 남부대로 429 대표전화 : 031-668-3399 문의: 010-9089-3399</p>
                    <hr>
                </div>    
            </div>
            
        </footer>
    </body>
</html>

ch1/mysite/templates/base1.html
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
        <!--<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>-->
        <!-- bootstrap -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">

        <style>
            #nav_bar {
                background-color: rgb(15,58,114);
            }
        </style>
    </head>

    <body>
        <!-- bootstrap -->
        <script src="http://code.jquery.com/jquery.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>


        <div id="nav_bar" class="navbar navbar-inverse navbar-fixed-top" style="background-color: rgb(15,58,114)">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="#">Bizchool</a>
                    <div class="nav-collapse collapse">
                    <ul class="nav">
                      <li class="active"><a href="#">학교소개</a></li>
                      <li><a href="#about">학교과목</a></li>
                      <li><a href="#contact">교육목표</a></li>
                      <li><a href="#">학교안내</a></li>
                    </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>

        <div class="container">

          <h1>Bootstrap starter template</h1>
          <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>

        </div> <!-- /container -->
        {% block content %}

        {% endblock %}

    </body>
</html>

ch1/mysite/templates/home.html
{% extends "realbase.html" %}

{% block content %}
<body>
	<style type="text/css">
        .jumbotron{
        }
    </style>
    <div class="jumbotron jumbotron-fruid" sytle="clear:both">
        <h1 class="text-center">bizchool 홈페이지</h1>
        <p class="text-center">홈페이지</p>
        <p class="text-center"><a href="#" class="btn btn-primary btn-lg" role="button">학교 둘러보기</a></p>
    </div>
</body>
{% endblock %}

ch1/mysite/templates/realbase.html
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="ko">
<head>
    <title>::Bizchool 대안학교::</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width", initial-scale="1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
    <body>
        <!-- navbar_top -->
        <style>
            .navbar-default{
                background-color: #0F3A72;
            }
            .container-fluid  ul  li{
                color: white;
            }

            @media (min-width: 768px){
                /* 큰 화면 전용 설정 */
                .container-fluid{
                    padding:0 20%;
                }
                .fcontent {
                    padding:0 20%;
                    display: flex;
                }
            }
            @media (max-width: 786px) {
                .fcontent{
                    display:flex;
                }
            }
        </style>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button style="border:2px solid #333333;" type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#list" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'homepage:home' %}">Bizchool</a>
                </div>
                <div class="collapse navbar-collapse" id="list">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'homepage:introduction' %}">학교안내</a></li>
                        <li><a href="{% url 'homepage:subject' %}">교과안내</a></li>
                        <li><a href="{% url 'homepage:news' %}">학교소식</a></li>
                        <li><a href="{% url 'homepage:entrance' %}">입학안내</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div style="height: 50px">

        </div>

        {% block content %}

        {% endblock %}    
        {% load static %}
        <footer style="background-color:#0F3A72">
                <br>
                <div class="container" style="display: flex;">
                    <div style="margin-left:1.5rem;"><img src="{% static 'img/logo1.png' %}" width="100px" height:"100px"></div>
                    <div style="color:rgb(175, 173, 173); margin-left:1.5rem;"><h5>Bizchool 대안학교<br>위치: 경기도 오산시 고현동 남부대로 427 비즈쿨 대안학교<br>TEL : 663-3399 | Number : 010-9089-3399 | E-mail : jyh8016@hanmail.net <br>Copyright &copy; 2018 by yoongyo.All Right Reserved</h5></div>
                </div>
                <br>
        </footer>
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

ch1/templates/base.html
 <!DOCTYPE html>
<html>
    <head>
    {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>
    </head>
    <body>
        <header>
            <div id="hdiv">
                <a href="{% url 'homepage:home' %}"><img src="{% static 'img/logo.png' %}" width="190px" height="30px"></a>
                <ul>
                    <li><a href="{% url 'homepage:introduction' %}">학교안내</a></li>
                    <li><a href="{% url 'homepage:subject' %}">교과안내</a></li>
                    <li><a href="{% url 'homepage:news' %}">학교소식</a></li>
                    <li><a href="{% url 'homepage:entrance' %}">입학안내</a></li>
                </ul>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <footer>
            <div id="fdiv">
                <div id="wrap">
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:introduction' %}">학교안내</a></li>
                            <hr>
                            <li>학교목표</li>
                            <li>교육과정</li>
                            <li>선생님 소개</li>
                            <li>오시는 길</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:subject' %}">교과안내</a></li>
                            <hr>
                            <li>공통과목</li>
                            <li>전공과목</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:news' %}">학교소식</a></li>
                            <hr>
                            <li>코딩캠프</li>
                        </ul>
                    </div>
                    <div class="fdiv">
                        <ul>
                            <li><a href="{% url 'homepage:entrance' %}">입학안내</a></li>
                            <hr>
                            <li>문의하기</li>
                            <li>전화</li>
                            <li>이메일</li>
                        </ul>
                    </div>
                </div>
                <div id="ffdiv">
                    <p>Copyright ⓒ Seoul Music High School All Rights Reserved.</p>
                    <hr>
                    <p style="color: white;">비즈쿨 대안학교<br>
                        경기도 오산시 고현동 남부대로 429 대표전화 : 031-668-3399 문의: 010-9089-3399</p>
                    <hr>
                </div>    
            </div>
            
        </footer>
    </body>
</html>